---
language: python
services: docker

install:
  # Install Ansible.
  - pip install ansible docker-py

script:
  # Build the Drupal environment.
  - 'ansible-playbook main.yml --extra-vars "{build_arm: false}"'

  # Verify we get a response from the site.
  - docker-compose up -d
  - |
    attempts=0
    max_attempts=60

    echo "Waiting for Drupal to complete setup."
    until $(curl --output /dev/null --silent --head --fail http://localhost/); do
        if [ ${attempts} -eq ${max_attempts} ];then
          echo "Timeout while waiting for Drupal to complete setup."
          exit 1
        fi

        printf '.'
        attempts=$(($attempts+1))
        sleep 5
    done
